/* Generated by powerful Codeforces Tool
 * Template written by Anton_lutsenko
 * Solution written by $%U%$
**/

#include <bits/stdc++.h>

#pragma comment(linker, "/stack:200000000")
#pragma GCC optimize("Ofast")
#pragma GCC target("sse,sse2,sse3,ssse3,sse4,popcnt,abm,mmx,avx,tune=native")
#pragma GCC optimization("unroll-loops")

// Settings
// #define UNORDERED
// #define FILE
// #define MANYTIMES
// #define int long long
// #define UPPER
// #define LOWER

const int MAXN = 1e5 + 10;
const int MOD = 1e9 + 7;
char *filein = "in.txt";
char *fileout = "out.txt";

#ifndef int
    const int INF = 1e9 + 10;
#else
    const int INF = 1e18 + 10;
#endif

#ifdef UNORDERED
    #define set unordered_set
    #define map unordered_map
#endif

#define ft first
#define sd second
#define all(s) s.begin(), s.end()
#define all2(s, n) s.begin(), s.begin() + n
#define pb push_back
#define mp make_pair
#define mt make_tuple
#define lb lower_bound
#define ub upper_bound
#define ins insert

#define REP(i) for (int i = 0; i < n; ++i)
#define REP1(i, e) for (int i = 0; i < e; ++i)
#define REP2(i, b, e) for (int i = b; i < e; ++i)
#define REP3(e, s) for (auto e : s)

using namespace std;

typedef vector<int> vint;
typedef array<int, MAXN> aint;
typedef array<double, MAXN> adouble;
typedef map<int, int> mint;
typedef set<int> sint;
typedef array<vint, MAXN> gr;
typedef pair<int, int> pint;

template <typename T>
ostream &operator<<(ostream &out, vector<T> &v) {
    for (auto elem : v) {
        out << elem << ' ';
    }
    return out;
}

template <typename T>
istream &operator>>(istream &in, vector<T> &v) {
    for (int i = 0; i < v.size(); ++i) {
        in >> v[i];
    }
    return in;
}

template <typename P, typename T>
ostream &operator<<(ostream &out, pair<T, P> &v) {
    out << v.ft << ' ' << v.sd;
    return out;
}

template <typename P, typename T>
istream &operator>>(istream &in, pair<T, P> &v) {
    in >> v.ft >> v.sd;
    return in;
}

template <typename T>
void input(array<T, MAXN> &a, int n) {
    REP(i) {
        cin >> a[i];
    }
}
template <typename T>
void print(vector<T> &a, int n, string sep = " ") {
    REP(i) {
        cout << a[i] << sep;
    }
}
template <typename T>
void print(array<T, MAXN> &a, int n, string sep = " ") {
    REP(i) {
        cout << a[i] << sep;
    }
}

void yes(int ret) {
    #ifdef UPPER
        cout << "YES" << endl;
    #else
        #ifdef LOWER
            cout << "yes" << endl;
        #else
            cout << "Yes" << endl;
        #endif
    #endif
    if (ret) {
        exit(0);
    }
}

void no(int ret) {
    #ifdef UPPER
        cout << "NO" << endl;
    #else
        #ifdef LOWER
            cout << "no" << endl;
        #else
            cout << "No" << endl;
        #endif
    #endif
    if (ret) {
        exit(0);
    }
}

signed solve() {

    return 0;
}

signed main() {
    #ifdef FILE
        freopen(filein, "r", stdin);
        freopen(fileout, "w", stdout);
    #endif
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    cout.tie(0);
    int k = 1;
    #ifdef MANYTIMES
        cin >> k;
    #endif
    while (k--) {
        solve();
    }
    return 0;
}
